version: '2'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    restart: always
    container_name: warehouse_db
    env_file: envs/prod.env
    environment:
      - log_destination=stderr
      - logging_collector=on
      - log_directory=/var/log/postgres_logs
    ports:
      - "5432:5432"
    volumes:
      - /db:/var/lib/postgresql/data
    networks:
      - docker_network

  app:
    env_file:
      - envs/prod.env
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    environment:
      DB_HOST: postgres

    stop_signal: SIGTERM
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - docker_network

networks:
  docker_network: